/********************************************************************************
** Form generated from reading UI file 'dialog_all.ui'
**
** Created by: Qt User Interface Compiler version 5.9.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_ALL_H
#define UI_DIALOG_ALL_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTextEdit>

QT_BEGIN_NAMESPACE

class Ui_Dialog_all
{
public:
    QDialogButtonBox *buttonBox;
    QTextEdit *textEdit;
    QLabel *order;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QTextEdit *type_id;
    QTextEdit *mac_source;
    QTextEdit *mac_des;
    QTextEdit *arp_ht;
    QTextEdit *eth_source;
    QTextEdit *ip_source;
    QTextEdit *arp_pt;
    QTextEdit *arp_hl;
    QTextEdit *arp_operation;
    QTextEdit *arp_pl;
    QTextEdit *eth_des;
    QTextEdit *ip_des;
    QTextEdit *ip_version;
    QTextEdit *icmp_type;
    QTextEdit *ip_des_address;
    QTextEdit *ip_source_address;
    QTextEdit *ip_hc;
    QTextEdit *ip_id;
    QTextEdit *ip_protocol;
    QTextEdit *ip_hl;
    QTextEdit *ip_tl;
    QTextEdit *ip_offset;
    QTextEdit *ip_ttl;
    QTextEdit *ip_tos;
    QTextEdit *tcp_source_port;
    QTextEdit *tcp_u_pointer;
    QTextEdit *tcp_ack_num;
    QTextEdit *tcp_des_port;
    QTextEdit *tcp_seq_num;
    QTextEdit *tcp_hl;
    QTextEdit *tcp_reserved;
    QTextEdit *tcp_flags;
    QTextEdit *tcp_checksum;
    QTextEdit *tcp_win_size;
    QTextEdit *udp_source_port;
    QTextEdit *udp_des_port;
    QTextEdit *udp_length;
    QTextEdit *udp_checksum;
    QTextEdit *udp_service;
    QTextEdit *icmp_protocol;
    QTextEdit *icmp_code;
    QTextEdit *icmp_id;
    QTextEdit *icmp_seq_num;
    QTextEdit *icmp_checksum;
    QPushButton *btn_next;
    QLabel *label_54;
    QTextEdit *number;
    QPushButton *pushButton;
    QTextEdit *tcp_protocol;

    void setupUi(QDialog *Dialog_all)
    {
        if (Dialog_all->objectName().isEmpty())
            Dialog_all->setObjectName(QStringLiteral("Dialog_all"));
        Dialog_all->resize(1221, 817);
        buttonBox = new QDialogButtonBox(Dialog_all);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(980, 790, 191, 20));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        textEdit = new QTextEdit(Dialog_all);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(-10, -10, 1191, 61));
        order = new QLabel(Dialog_all);
        order->setObjectName(QStringLiteral("order"));
        order->setGeometry(QRect(470, 70, 251, 16));
        label_2 = new QLabel(Dialog_all);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 90, 681, 41));
        label_3 = new QLabel(Dialog_all);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 130, 151, 16));
        label_4 = new QLabel(Dialog_all);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 170, 181, 21));
        label_5 = new QLabel(Dialog_all);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 210, 201, 31));
        label_7 = new QLabel(Dialog_all);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 240, 681, 21));
        label_8 = new QLabel(Dialog_all);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 270, 111, 31));
        label_9 = new QLabel(Dialog_all);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 310, 111, 21));
        label_10 = new QLabel(Dialog_all);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 350, 121, 16));
        label_11 = new QLabel(Dialog_all);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(260, 320, 121, 21));
        label_12 = new QLabel(Dialog_all);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(260, 280, 151, 16));
        label_13 = new QLabel(Dialog_all);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 390, 201, 31));
        label_14 = new QLabel(Dialog_all);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(370, 400, 131, 16));
        label_15 = new QLabel(Dialog_all);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 430, 231, 21));
        label_16 = new QLabel(Dialog_all);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(370, 440, 201, 16));
        label_17 = new QLabel(Dialog_all);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(0, 470, 681, 31));
        label_18 = new QLabel(Dialog_all);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(130, 520, 101, 21));
        label_19 = new QLabel(Dialog_all);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(130, 560, 111, 16));
        label_20 = new QLabel(Dialog_all);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(380, 600, 67, 17));
        label_21 = new QLabel(Dialog_all);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(130, 600, 111, 21));
        label_22 = new QLabel(Dialog_all);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(130, 640, 111, 16));
        label_23 = new QLabel(Dialog_all);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(380, 520, 67, 20));
        label_24 = new QLabel(Dialog_all);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(380, 560, 67, 17));
        label_25 = new QLabel(Dialog_all);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(370, 640, 67, 17));
        label_26 = new QLabel(Dialog_all);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(130, 680, 141, 21));
        label_27 = new QLabel(Dialog_all);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(130, 720, 131, 21));
        label_28 = new QLabel(Dialog_all);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(130, 750, 161, 21));
        label_29 = new QLabel(Dialog_all);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(700, 100, 471, 31));
        label_30 = new QLabel(Dialog_all);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(700, 140, 111, 21));
        label_31 = new QLabel(Dialog_all);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(700, 180, 131, 21));
        label_32 = new QLabel(Dialog_all);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(960, 330, 67, 17));
        label_33 = new QLabel(Dialog_all);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(700, 220, 141, 21));
        label_34 = new QLabel(Dialog_all);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(700, 260, 201, 16));
        label_35 = new QLabel(Dialog_all);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(960, 140, 121, 16));
        label_36 = new QLabel(Dialog_all);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(960, 180, 111, 21));
        label_37 = new QLabel(Dialog_all);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(960, 220, 67, 17));
        label_38 = new QLabel(Dialog_all);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(700, 300, 111, 21));
        label_39 = new QLabel(Dialog_all);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(960, 300, 91, 21));
        label_40 = new QLabel(Dialog_all);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(700, 330, 121, 21));
        label_41 = new QLabel(Dialog_all);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(700, 380, 461, 31));
        label_42 = new QLabel(Dialog_all);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(700, 420, 101, 21));
        label_43 = new QLabel(Dialog_all);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(700, 470, 131, 16));
        label_44 = new QLabel(Dialog_all);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(700, 520, 67, 17));
        label_45 = new QLabel(Dialog_all);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(960, 430, 67, 17));
        label_46 = new QLabel(Dialog_all);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(960, 460, 91, 21));
        label_47 = new QLabel(Dialog_all);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(700, 550, 471, 31));
        label_48 = new QLabel(Dialog_all);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(700, 580, 91, 21));
        label_49 = new QLabel(Dialog_all);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(700, 700, 67, 17));
        label_50 = new QLabel(Dialog_all);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(700, 630, 101, 16));
        label_51 = new QLabel(Dialog_all);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(950, 630, 81, 16));
        label_52 = new QLabel(Dialog_all);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(700, 660, 151, 16));
        label_53 = new QLabel(Dialog_all);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(950, 590, 101, 21));
        type_id = new QTextEdit(Dialog_all);
        type_id->setObjectName(QStringLiteral("type_id"));
        type_id->setGeometry(QRect(220, 130, 411, 31));
        mac_source = new QTextEdit(Dialog_all);
        mac_source->setObjectName(QStringLiteral("mac_source"));
        mac_source->setGeometry(QRect(220, 170, 411, 31));
        mac_des = new QTextEdit(Dialog_all);
        mac_des->setObjectName(QStringLiteral("mac_des"));
        mac_des->setGeometry(QRect(220, 210, 411, 31));
        arp_ht = new QTextEdit(Dialog_all);
        arp_ht->setObjectName(QStringLiteral("arp_ht"));
        arp_ht->setGeometry(QRect(140, 270, 101, 31));
        eth_source = new QTextEdit(Dialog_all);
        eth_source->setObjectName(QStringLiteral("eth_source"));
        eth_source->setGeometry(QRect(240, 390, 111, 31));
        ip_source = new QTextEdit(Dialog_all);
        ip_source->setObjectName(QStringLiteral("ip_source"));
        ip_source->setGeometry(QRect(530, 390, 111, 31));
        arp_pt = new QTextEdit(Dialog_all);
        arp_pt->setObjectName(QStringLiteral("arp_pt"));
        arp_pt->setGeometry(QRect(140, 310, 101, 31));
        arp_hl = new QTextEdit(Dialog_all);
        arp_hl->setObjectName(QStringLiteral("arp_hl"));
        arp_hl->setGeometry(QRect(140, 350, 101, 31));
        arp_operation = new QTextEdit(Dialog_all);
        arp_operation->setObjectName(QStringLiteral("arp_operation"));
        arp_operation->setGeometry(QRect(350, 270, 101, 31));
        arp_pl = new QTextEdit(Dialog_all);
        arp_pl->setObjectName(QStringLiteral("arp_pl"));
        arp_pl->setGeometry(QRect(380, 310, 71, 31));
        eth_des = new QTextEdit(Dialog_all);
        eth_des->setObjectName(QStringLiteral("eth_des"));
        eth_des->setGeometry(QRect(240, 430, 111, 31));
        ip_des = new QTextEdit(Dialog_all);
        ip_des->setObjectName(QStringLiteral("ip_des"));
        ip_des->setGeometry(QRect(530, 430, 111, 31));
        ip_version = new QTextEdit(Dialog_all);
        ip_version->setObjectName(QStringLiteral("ip_version"));
        ip_version->setGeometry(QRect(260, 510, 81, 31));
        icmp_type = new QTextEdit(Dialog_all);
        icmp_type->setObjectName(QStringLiteral("icmp_type"));
        icmp_type->setGeometry(QRect(830, 580, 91, 31));
        ip_des_address = new QTextEdit(Dialog_all);
        ip_des_address->setObjectName(QStringLiteral("ip_des_address"));
        ip_des_address->setGeometry(QRect(380, 750, 181, 31));
        ip_source_address = new QTextEdit(Dialog_all);
        ip_source_address->setObjectName(QStringLiteral("ip_source_address"));
        ip_source_address->setGeometry(QRect(380, 710, 181, 31));
        ip_hc = new QTextEdit(Dialog_all);
        ip_hc->setObjectName(QStringLiteral("ip_hc"));
        ip_hc->setGeometry(QRect(380, 670, 181, 31));
        ip_id = new QTextEdit(Dialog_all);
        ip_id->setObjectName(QStringLiteral("ip_id"));
        ip_id->setGeometry(QRect(260, 630, 81, 31));
        ip_protocol = new QTextEdit(Dialog_all);
        ip_protocol->setObjectName(QStringLiteral("ip_protocol"));
        ip_protocol->setGeometry(QRect(480, 630, 81, 31));
        ip_hl = new QTextEdit(Dialog_all);
        ip_hl->setObjectName(QStringLiteral("ip_hl"));
        ip_hl->setGeometry(QRect(260, 550, 81, 31));
        ip_tl = new QTextEdit(Dialog_all);
        ip_tl->setObjectName(QStringLiteral("ip_tl"));
        ip_tl->setGeometry(QRect(260, 590, 81, 31));
        ip_offset = new QTextEdit(Dialog_all);
        ip_offset->setObjectName(QStringLiteral("ip_offset"));
        ip_offset->setGeometry(QRect(480, 510, 81, 31));
        ip_ttl = new QTextEdit(Dialog_all);
        ip_ttl->setObjectName(QStringLiteral("ip_ttl"));
        ip_ttl->setGeometry(QRect(480, 550, 81, 31));
        ip_tos = new QTextEdit(Dialog_all);
        ip_tos->setObjectName(QStringLiteral("ip_tos"));
        ip_tos->setGeometry(QRect(480, 590, 81, 31));
        tcp_source_port = new QTextEdit(Dialog_all);
        tcp_source_port->setObjectName(QStringLiteral("tcp_source_port"));
        tcp_source_port->setGeometry(QRect(850, 130, 91, 31));
        tcp_u_pointer = new QTextEdit(Dialog_all);
        tcp_u_pointer->setObjectName(QStringLiteral("tcp_u_pointer"));
        tcp_u_pointer->setGeometry(QRect(850, 330, 91, 31));
        tcp_ack_num = new QTextEdit(Dialog_all);
        tcp_ack_num->setObjectName(QStringLiteral("tcp_ack_num"));
        tcp_ack_num->setGeometry(QRect(900, 250, 261, 31));
        tcp_des_port = new QTextEdit(Dialog_all);
        tcp_des_port->setObjectName(QStringLiteral("tcp_des_port"));
        tcp_des_port->setGeometry(QRect(850, 170, 91, 31));
        tcp_seq_num = new QTextEdit(Dialog_all);
        tcp_seq_num->setObjectName(QStringLiteral("tcp_seq_num"));
        tcp_seq_num->setGeometry(QRect(850, 210, 91, 31));
        tcp_hl = new QTextEdit(Dialog_all);
        tcp_hl->setObjectName(QStringLiteral("tcp_hl"));
        tcp_hl->setGeometry(QRect(1070, 130, 91, 31));
        tcp_reserved = new QTextEdit(Dialog_all);
        tcp_reserved->setObjectName(QStringLiteral("tcp_reserved"));
        tcp_reserved->setGeometry(QRect(1070, 170, 91, 31));
        tcp_flags = new QTextEdit(Dialog_all);
        tcp_flags->setObjectName(QStringLiteral("tcp_flags"));
        tcp_flags->setGeometry(QRect(1070, 210, 91, 31));
        tcp_checksum = new QTextEdit(Dialog_all);
        tcp_checksum->setObjectName(QStringLiteral("tcp_checksum"));
        tcp_checksum->setGeometry(QRect(1070, 290, 91, 31));
        tcp_win_size = new QTextEdit(Dialog_all);
        tcp_win_size->setObjectName(QStringLiteral("tcp_win_size"));
        tcp_win_size->setGeometry(QRect(850, 290, 91, 31));
        udp_source_port = new QTextEdit(Dialog_all);
        udp_source_port->setObjectName(QStringLiteral("udp_source_port"));
        udp_source_port->setGeometry(QRect(830, 420, 91, 31));
        udp_des_port = new QTextEdit(Dialog_all);
        udp_des_port->setObjectName(QStringLiteral("udp_des_port"));
        udp_des_port->setGeometry(QRect(830, 460, 91, 31));
        udp_length = new QTextEdit(Dialog_all);
        udp_length->setObjectName(QStringLiteral("udp_length"));
        udp_length->setGeometry(QRect(1070, 420, 91, 31));
        udp_checksum = new QTextEdit(Dialog_all);
        udp_checksum->setObjectName(QStringLiteral("udp_checksum"));
        udp_checksum->setGeometry(QRect(1070, 460, 91, 31));
        udp_service = new QTextEdit(Dialog_all);
        udp_service->setObjectName(QStringLiteral("udp_service"));
        udp_service->setGeometry(QRect(900, 510, 261, 31));
        icmp_protocol = new QTextEdit(Dialog_all);
        icmp_protocol->setObjectName(QStringLiteral("icmp_protocol"));
        icmp_protocol->setGeometry(QRect(900, 700, 261, 31));
        icmp_code = new QTextEdit(Dialog_all);
        icmp_code->setObjectName(QStringLiteral("icmp_code"));
        icmp_code->setGeometry(QRect(830, 620, 91, 31));
        icmp_id = new QTextEdit(Dialog_all);
        icmp_id->setObjectName(QStringLiteral("icmp_id"));
        icmp_id->setGeometry(QRect(1070, 620, 91, 31));
        icmp_seq_num = new QTextEdit(Dialog_all);
        icmp_seq_num->setObjectName(QStringLiteral("icmp_seq_num"));
        icmp_seq_num->setGeometry(QRect(900, 660, 261, 31));
        icmp_checksum = new QTextEdit(Dialog_all);
        icmp_checksum->setObjectName(QStringLiteral("icmp_checksum"));
        icmp_checksum->setGeometry(QRect(1070, 580, 91, 31));
        btn_next = new QPushButton(Dialog_all);
        btn_next->setObjectName(QStringLiteral("btn_next"));
        btn_next->setGeometry(QRect(800, 60, 151, 41));
        label_54 = new QLabel(Dialog_all);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(700, 740, 361, 31));
        number = new QTextEdit(Dialog_all);
        number->setObjectName(QStringLiteral("number"));
        number->setGeometry(QRect(1060, 740, 101, 31));
        pushButton = new QPushButton(Dialog_all);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(740, 780, 121, 31));
        tcp_protocol = new QTextEdit(Dialog_all);
        tcp_protocol->setObjectName(QStringLiteral("tcp_protocol"));
        tcp_protocol->setGeometry(QRect(1070, 330, 91, 31));

        retranslateUi(Dialog_all);
        QObject::connect(buttonBox, SIGNAL(accepted()), Dialog_all, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), Dialog_all, SLOT(reject()));

        QMetaObject::connectSlotsByName(Dialog_all);
    } // setupUi

    void retranslateUi(QDialog *Dialog_all)
    {
        Dialog_all->setWindowTitle(QApplication::translate("Dialog_all", "Capture All packets", Q_NULLPTR));
        textEdit->setHtml(QApplication::translate("Dialog_all", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">Capture All packets</span></p></body></html>", Q_NULLPTR));
        order->setText(QApplication::translate("Dialog_all", "The %d  packet is captured", Q_NULLPTR));
        label_2->setText(QApplication::translate("Dialog_all", "----------------------------------------------------  Ethernet Protocol(Link Layer) --------------------------------------------------------- ", Q_NULLPTR));
        label_3->setText(QApplication::translate("Dialog_all", "Ethernet type is: ", Q_NULLPTR));
        label_4->setText(QApplication::translate("Dialog_all", "Mac source address is : ", Q_NULLPTR));
        label_5->setText(QApplication::translate("Dialog_all", "Mac destination address is: ", Q_NULLPTR));
        label_7->setText(QApplication::translate("Dialog_all", "----------------------------------------------------   ARP Protocol(Network Layer) --------------------------------------------------------- ", Q_NULLPTR));
        label_8->setText(QApplication::translate("Dialog_all", "Hardware Type:", Q_NULLPTR));
        label_9->setText(QApplication::translate("Dialog_all", "Protocol Type:", Q_NULLPTR));
        label_10->setText(QApplication::translate("Dialog_all", "Hardware Length:", Q_NULLPTR));
        label_11->setText(QApplication::translate("Dialog_all", "Protocol Length:", Q_NULLPTR));
        label_12->setText(QApplication::translate("Dialog_all", "Operation:", Q_NULLPTR));
        label_13->setText(QApplication::translate("Dialog_all", "Ethernet Source Address is:", Q_NULLPTR));
        label_14->setText(QApplication::translate("Dialog_all", "Source IP Address:", Q_NULLPTR));
        label_15->setText(QApplication::translate("Dialog_all", "Ethernet Destination Address id:", Q_NULLPTR));
        label_16->setText(QApplication::translate("Dialog_all", "Destination IP Address:", Q_NULLPTR));
        label_17->setText(QApplication::translate("Dialog_all", "-----------------------------------------------------   IP Protocol (Network Layer) ----------------------------------------------------  ", Q_NULLPTR));
        label_18->setText(QApplication::translate("Dialog_all", "IP version: ", Q_NULLPTR));
        label_19->setText(QApplication::translate("Dialog_all", "Header length: ", Q_NULLPTR));
        label_20->setText(QApplication::translate("Dialog_all", "TOS: ", Q_NULLPTR));
        label_21->setText(QApplication::translate("Dialog_all", "Total length: ", Q_NULLPTR));
        label_22->setText(QApplication::translate("Dialog_all", "Identification: ", Q_NULLPTR));
        label_23->setText(QApplication::translate("Dialog_all", "Offset: ", Q_NULLPTR));
        label_24->setText(QApplication::translate("Dialog_all", "TTL: ", Q_NULLPTR));
        label_25->setText(QApplication::translate("Dialog_all", "Protocol: ", Q_NULLPTR));
        label_26->setText(QApplication::translate("Dialog_all", "Header checksum: ", Q_NULLPTR));
        label_27->setText(QApplication::translate("Dialog_all", "Source address: ", Q_NULLPTR));
        label_28->setText(QApplication::translate("Dialog_all", "Destination address: ", Q_NULLPTR));
        label_29->setText(QApplication::translate("Dialog_all", "--------------------------- TCP Protocol(Transport Layer) --------------------------------------  ", Q_NULLPTR));
        label_30->setText(QApplication::translate("Dialog_all", "Source Port: ", Q_NULLPTR));
        label_31->setText(QApplication::translate("Dialog_all", "Destination Port: ", Q_NULLPTR));
        label_32->setText(QApplication::translate("Dialog_all", "Protocol:", Q_NULLPTR));
        label_33->setText(QApplication::translate("Dialog_all", "Sequence number: ", Q_NULLPTR));
        label_34->setText(QApplication::translate("Dialog_all", "Acknowledgement number: ", Q_NULLPTR));
        label_35->setText(QApplication::translate("Dialog_all", "Header length: ", Q_NULLPTR));
        label_36->setText(QApplication::translate("Dialog_all", "Reserved: ", Q_NULLPTR));
        label_37->setText(QApplication::translate("Dialog_all", "Flags: ", Q_NULLPTR));
        label_38->setText(QApplication::translate("Dialog_all", "Window Size: ", Q_NULLPTR));
        label_39->setText(QApplication::translate("Dialog_all", "Checksum: ", Q_NULLPTR));
        label_40->setText(QApplication::translate("Dialog_all", "Urgent pointer: ", Q_NULLPTR));
        label_41->setText(QApplication::translate("Dialog_all", "-------------------------- UDP Protocol(Transport Layer) ------------------------------", Q_NULLPTR));
        label_42->setText(QApplication::translate("Dialog_all", "Source port:", Q_NULLPTR));
        label_43->setText(QApplication::translate("Dialog_all", "Destination port:", Q_NULLPTR));
        label_44->setText(QApplication::translate("Dialog_all", "Service:", Q_NULLPTR));
        label_45->setText(QApplication::translate("Dialog_all", "Length: ", Q_NULLPTR));
        label_46->setText(QApplication::translate("Dialog_all", "Checksum:", Q_NULLPTR));
        label_47->setText(QApplication::translate("Dialog_all", "-------------------------- ICMP Protocol(Transport Layer) ------------------------------", Q_NULLPTR));
        label_48->setText(QApplication::translate("Dialog_all", "ICMP Type: ", Q_NULLPTR));
        label_49->setText(QApplication::translate("Dialog_all", "Protocol:", Q_NULLPTR));
        label_50->setText(QApplication::translate("Dialog_all", "ICMP Code: ", Q_NULLPTR));
        label_51->setText(QApplication::translate("Dialog_all", "Identifier: ", Q_NULLPTR));
        label_52->setText(QApplication::translate("Dialog_all", "Sequence Number: ", Q_NULLPTR));
        label_53->setText(QApplication::translate("Dialog_all", "Checksum: ", Q_NULLPTR));
        btn_next->setText(QApplication::translate("Dialog_all", "NEXT!", Q_NULLPTR));
        label_54->setText(QApplication::translate("Dialog_all", "Please enter the number of packets to capture :", Q_NULLPTR));
        pushButton->setText(QApplication::translate("Dialog_all", "Start now!", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class Dialog_all: public Ui_Dialog_all {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_ALL_H
